name: Deploy to Raspi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Copy application files to Pi
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_KEY }}
        source: "."
        target: "~/app"
        strip_components: 1
        port: 22
        timeout: 15m
        command_timeout: 25m

    - name: Setup and Deploy on RasPi
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_KEY }}
        envs: PACK
        script: |
          set -e
          cd ~/app
          
          python -c "import numpy, scipy, matplotlib; print('✓ Scientific packages loaded')"
          python -c "import flask, gunicorn; print('✓ Web packages loaded')"

          echo "Set systemd service..."
          if [ -f "conf/flask-app.service" ]; then
            sed "s/\${USER}/${{ secrets.PI_USER }}/g" conf/flask-app.service | sudo tee /etc/systemd/system/flask-app.service > /dev/null
            sudo systemctl daemon-reload
          else
            echo "Warning: conf/flask-app.service not found"
            exit 1
          fi

          echo "Restart service ..."
          sudo systemctl enable flask-app.service
          sudo systemctl restart flask-app.service

          echo "Service status:"          
          sudo systemctl status flask-app.service --no-pager

          echo "Verify application ..."
          sleep 5
          curl -f --connect-timeout 10 --max-time 30 http://localhost:5001/ || echo "Application not running (yet)"

          echo "✅ Deploy complete"
        timeout: 15m
        command_timeout: 25m
