name: Deploy to Raspi (No Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Copy application files to Pi
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_KEY }}
        source: "."
        target: "~/app"
        strip_components: 1
        port: 22
        timeout: 15m
        command_timeout: 25m

    - name: Setup and Deploy on RasPi
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_KEY }}
        script: |
          cd ~/app
          
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-venv
          
          python3 -m venv venv
          
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r pack.txt

          sudo tee /etc/systemd/system/flask-app.service > /dev/null << EOF
          [Unit]
          Description=Flask App
          After=network.target

          [Service]
          Type=simple
          User=${{ secrets.PI_USER }}
          WorkingDirectory=/home/${{ secrets.PI_USER }}/app
          Environment=PATH=/home/${{ secrets.PI_USER }}/app/venv/bin
          ExecStart=/home/${{ secrets.PI_USER }}/app/venv/bin/gunicorn --bind 0.0.0.0:5000 --workers 1 --timeout 120 app:app
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target
          EOF
          
          sudo systemctl daemon-reload
          sudo systemctl enable flask-app.service
          sudo systemctl restart flask-app.service
          
          echo "Service status:"
          sudo systemctl status flask-app.service
        timeout: 15m
        command_timeout: 25m
